# Generated by Django 5.2.9 on 2026-02-03 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauth',
            name='role',
            field=models.CharField(choices=[('Agent', 'Agent'), ('Client', 'Client')], default='Client', max_length=10),
        ),
    ]
