# Generated by Django 5.2.9 on 2026-02-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userauth_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauth',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userauth',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userauth',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userauth',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
