# Generated by Django 5.2.9 on 2026-02-26 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_userauth_city_userauth_company_userauth_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauth',
            name='agency_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
