# Generated by Django 5.2.9 on 2026-02-22 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('budget_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('job_type', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('closed', 'Closed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('ai_prompt', models.TextField(blank=True)),
                ('applicants_count', models.PositiveIntegerField(default=0)),
                ('shortlisted_count', models.PositiveIntegerField(default=0)),
                ('selftapes_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs_assigned', to=settings.AUTH_USER_MODEL)),
                ('job_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='jobs_talent_status_b1b232_idx'), models.Index(fields=['job_created_by'], name='jobs_talent_job_cre_9a1d01_idx'), models.Index(fields=['job_assigned_to'], name='jobs_talent_job_ass_05a375_idx'), models.Index(fields=['created_at'], name='jobs_talent_created_82fcef_idx')],
            },
        ),
    ]
