# Generated by Django 5.2.9 on 2026-02-22 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_talent', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Talent',
            fields=[
                ('talent_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(blank=True, max_length=255)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bust', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('waist', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hips', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('shoe_size', models.PositiveIntegerField(blank=True, null=True)),
                ('eye_color', models.CharField(blank=True, max_length=64)),
                ('hair_type', models.CharField(blank=True, max_length=64)),
                ('hair_color', models.CharField(blank=True, max_length=64)),
                ('skin_color', models.CharField(blank=True, max_length=64)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('continent', models.CharField(blank=True, max_length=64)),
                ('country', models.CharField(blank=True, max_length=64)),
                ('is_available', models.BooleanField(default=True)),
                ('available_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talents_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TalentImage',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='talents/images/')),
                ('is_primary', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='jobs_talent.talent')),
            ],
            options={
                'ordering': ['-is_primary', 'sort_order', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='talent',
            index=models.Index(fields=['added_by_agent'], name='jobs_talent_added_b_66d284_idx'),
        ),
        migrations.AddIndex(
            model_name='talent',
            index=models.Index(fields=['is_available'], name='jobs_talent_is_avai_90c67e_idx'),
        ),
        migrations.AddIndex(
            model_name='talent',
            index=models.Index(fields=['country'], name='jobs_talent_country_93ac5f_idx'),
        ),
        migrations.AddIndex(
            model_name='talent',
            index=models.Index(fields=['gender'], name='jobs_talent_gender_af5a5b_idx'),
        ),
        migrations.AddIndex(
            model_name='talentimage',
            index=models.Index(fields=['talent', 'is_primary'], name='jobs_talent_talent__a232bd_idx'),
        ),
        migrations.AddIndex(
            model_name='talentimage',
            index=models.Index(fields=['talent', 'sort_order'], name='jobs_talent_talent__0ce22c_idx'),
        ),
        migrations.AddConstraint(
            model_name='talentimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('talent',), name='unique_primary_image_per_talent'),
        ),
    ]
